error handling updated

diff --git a/.github/workflows/manage-ec2.yml b/.github/workflows/manage-ec2.yml
--- a/.github/workflows/manage-ec2.yml
+++ b/.github/workflows/manage-ec2.yml
@@ -84,7 +84,7 @@ jobs:
                   ;;
                 restart)
                   echo "Restarting PM2 process ${{ github.event.inputs.process_name }}"
-                  pm2 restart ${{ github.event.inputs.process_name }} || { echo "Failed to restart PM2 process"; exit 1; }
+                  pm2 restart ${{ github.event.inputs.process_name }} --update-env || { echo "Failed to restart PM2 process"; exit 1; }
                   ;;
                 status)
                   echo "Getting status of PM2 process ${{ github.event.inputs.process_name }}"
